//! The FK's ground truth: MuJoCo's own `mj_kinematics`.
//!
//! The fixture is 64 random joint configurations with every site's pose as
//! MuJoCo computed it, generated by `scripts/gen_fixtures.py` in the
//! `microduck_kinematics_rs` repo (run via `uv`) against the same
//! `robot_walk.xml` embedded here. Regenerate it whenever the MJCF changes —
//! the parity is exact (1e-6), so any real divergence fails loudly.

use std::collections::HashMap;

use kinematics::Model;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    samples: Vec<Sample>,
}

#[derive(Deserialize)]
struct Sample {
    joints: HashMap<String, f64>,
    sites: HashMap<String, SitePose>,
}

#[derive(Deserialize)]
struct SitePose {
    pos: [f64; 3],
    quat: [f64; 4],
}

#[test]
fn alpha_matches_mujoco_on_every_site_of_64_random_poses() {
    const POS_TOL: f64 = 1e-6; // metres
    const QUAT_TOL: f64 = 1e-6; // unitless

    let fixture: Fixture =
        serde_json::from_str(include_str!("fixtures/fk_alpha.json")).expect("fixture parses");
    let model = Model::alpha();

    assert!(!fixture.samples.is_empty());
    for (i, sample) in fixture.samples.iter().enumerate() {
        let mut angles = vec![0.0; model.num_joints()];
        for (name, &angle) in &sample.joints {
            let idx = model
                .joint_index(name)
                .unwrap_or_else(|| panic!("fixture joint {name:?} missing from model"));
            angles[idx] = angle;
        }

        for (site_name, expected) in &sample.sites {
            let site = model
                .site(site_name)
                .unwrap_or_else(|| panic!("fixture site {site_name:?} missing from model"));
            let got = model.site_pose(site, &angles);

            let pos_err = expected
                .pos
                .iter()
                .zip(got.pos)
                .map(|(a, b)| (a - b).abs())
                .fold(0.0, f64::max);
            assert!(
                pos_err < POS_TOL,
                "sample #{i} site {site_name:?}: pos off by {pos_err} \
                 (expected {:?}, got {:?})",
                expected.pos,
                got.pos,
            );

            // q and -q are the same rotation; accept whichever sign MuJoCo chose.
            let got_q = got.quat.wxyz();
            let err = |sign: f64| {
                expected
                    .quat
                    .iter()
                    .zip(got_q)
                    .map(|(a, b)| (a - sign * b).abs())
                    .fold(0.0, f64::max)
            };
            let quat_err = err(1.0).min(err(-1.0));
            assert!(
                quat_err < QUAT_TOL,
                "sample #{i} site {site_name:?}: quat off by {quat_err} \
                 (expected {:?}, got {:?})",
                expected.quat,
                got_q,
            );
        }
    }
}
