//! Sole anchor points for the contact odometry, in each foot's site frame
//! (X front/back, Y left/right, Z up), metres.
//!
//! GENERATED by microduck_rl/scripts/odom_anchor_points.py — do not edit:
//!   odom_anchor_points.py --rust /home/antoine/Pollen/microduck/odometry/src/anchors.rs
//! from src/mjlab_microduck/robot/microduck/scene.xml.

/// A named set of candidate contact points, one list per foot.
pub struct AnchorSet {
    pub name: &'static str,
    pub left: &'static [[f64; 3]],
    pub right: &'static [[f64; 3]],
}

impl AnchorSet {
    /// Points for foot 0 (left) or 1 (right).
    pub fn foot(&self, foot: usize) -> &'static [[f64; 3]] {
        if foot == 0 { self.left } else { self.right }
    }
}

/// Legacy: the v1.5 sole bbox on the site's Z = 0 plane, both feet alike.
pub const V15: AnchorSet = AnchorSet {
    name: "v15",
    left: &[
        [0.027000, 0.020600, 0.000000],
        [0.027000, -0.020600, 0.000000],
        [-0.027000, -0.020600, 0.000000],
        [-0.027000, 0.020600, 0.000000],
    ],
    right: &[
        [0.027000, 0.020600, 0.000000],
        [0.027000, -0.020600, 0.000000],
        [-0.027000, -0.020600, 0.000000],
        [-0.027000, 0.020600, 0.000000],
    ],
};

/// The four corners of the alpha sole's flat contact patch, on the mesh.
pub const ALPHA4: AnchorSet = AnchorSet {
    name: "alpha4",
    left: &[
        [0.024844, 0.012452, 0.001414],
        [0.024029, -0.012395, -0.000680],
        [-0.011047, -0.013121, -0.000751],
        [-0.011862, 0.013177, 0.001515],
    ],
    right: &[
        [0.024029, 0.012395, -0.000680],
        [0.024844, -0.012452, 0.001415],
        [-0.011862, -0.013177, 0.001516],
        [-0.011047, 0.013121, -0.000751],
    ],
};

/// A 4x4 grid over the whole alpha footprint (bevels included), on the mesh.
pub const ALPHA16: AnchorSet = AnchorSet {
    name: "alpha16",
    left: &[
        [-0.018300, -0.019510, 0.005894],
        [-0.001500, -0.019659, 0.001516],
        [0.015500, -0.019659, 0.002082],
        [0.031699, -0.019061, 0.005531],
        [-0.018500, -0.006960, 0.002891],
        [-0.001500, -0.006960, -0.000607],
        [0.015500, -0.006960, -0.000573],
        [0.032500, -0.006960, 0.002863],
        [-0.018500, 0.005740, 0.003709],
        [-0.001500, 0.005740, 0.000500],
        [0.015500, 0.005740, 0.000474],
        [0.032500, 0.005740, 0.003683],
        [-0.018300, 0.018290, 0.007998],
        [-0.001500, 0.018439, 0.003859],
        [0.015500, 0.018439, 0.004318],
        [0.031699, 0.017841, 0.007574],
    ],
    right: &[
        [-0.018300, -0.018290, 0.007998],
        [-0.001500, -0.018439, 0.003859],
        [0.015500, -0.018439, 0.004320],
        [0.031699, -0.017841, 0.007574],
        [-0.018500, -0.005740, 0.003712],
        [-0.001500, -0.005740, 0.000500],
        [0.015500, -0.005740, 0.000474],
        [0.032500, -0.005740, 0.003681],
        [-0.018500, 0.006960, 0.002893],
        [-0.001500, 0.006960, -0.000607],
        [0.015500, 0.006960, -0.000573],
        [0.032500, 0.006960, 0.002863],
        [-0.018300, 0.019510, 0.005894],
        [-0.001500, 0.019659, 0.001516],
        [0.015500, 0.019659, 0.002080],
        [0.031699, 0.019061, 0.005531],
    ],
};
